version: "3.9"

services:
  nuxt-app:
    build:
      context: .
    container_name: nuxt_app
    env_file:
      - .env          # <- makes your SMTP/TURNSTILE variables available
    ports:
      - "3000:3000"
    restart: unless-stopped
